apiVersion: v1
kind: Pod
metadata:
  name: jenkins-build
  namespace: jenkins
  labels:
    app: jenkins-build
    version: 1.0v
    workLoad: multi-container
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: payload
            operator: In
            values:
            - automation
            - operation 
            - management
  containers:
    - name: docker
      image: docker:19.03
      securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 0
      command:
        - cat
      tty: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
    - name: helm
      image: lachlanevenson/k8s-helm:v3.2.4
      tty: true
      command:
        - cat
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
  # resources:
  #   requests:
  #     memory: "100Mi"
  #     cpu: "250m"
  #   limits:
  #     memory: "200Mi"
  #     cpu: "500m"